language: android
android:
  components:
    - build-tools-31.0.0
    - android-30
    - add-on
    - extra
    - platform-tools
    - tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-30

before_install:
  - yes | sdkmanager "platforms;android-30"
  - chmod +x gradlew

script: ./gradlew :app:build

deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file: app/build/outputs/apk/release/app-release.apk
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
      - morvai.daniel96@gmail.com
    on_failure: always
    on_success: always